### PR TITLE
[JENKINS-64228] Table to div compatibility + Update the minimum Jenkins core requirement to 2.204.6 + Update Parent POM to a recent version

### PR DESCRIPTION
**Pull request by res0nance**
Most importantly to prevent the page from breaking with newer jenkins cores

### CODE REVIEW

**Comment by res0nance** [comment]
@moxun1639 could you take a look at this PR its affecting users on the latest core

**Comment by moxun1639** [comment]
Thank you very much!

**Comment by timja** [comment]
Was there an issue during release @moxun1639 ?

The new plugin doesn't seem to have appeared, https://get.jenkins.io/plugins/content-replace/

**Comment by moxun1639** [comment]
There was an authorization error whe "mvn release:prepare release:perform" was executed
``` Transfer failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/content-replace/1.6.0/content-replace-1.6.0.hpi 401 Unauthorized```

**Comment by timja** [comment]
Right the last time you released was in January, all passwords were reset in March.

If you reset your password via https://beta.accounts.jenkins.io, and log in to https://repo.jenkins-ci.org that should sort it out.

You'll need to update your encrypted password or API token in your `~/.m2/settings.xml` as well

**Pull request merged**
